name: Feature request
description: Suggest an enhancement
title: "[feature] "
labels: ["enhancement"]
body:
  - type: textarea
    id: idea
    attributes:
      label: Idea
      description: Describe the feature you want.
    validations:
      required: true
